default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  reconnect: false
  database: watermark
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: watermark.c5iye2qcg1ir.us-east-1.rds.amazonaws.com
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
